# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import gmaps.datasets
import os
import ipywidgets as widgets


# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data=pd.read_csv('weather_data')

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
locations = weather_data[['Lat','Lon']].astype(float)
weights = weather_data['Humidity'].astype(float)
fig = gmaps.figure(center=(20.0,0), zoom_level=2)
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights))
fig
heatmap_layer = gmaps.heatmap_layer(
    locations, weights=weights, dissipating=False, max_intensity=100, point_radius=1)
fig.add_layer(heatmap_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [40]:
weath_dat=weather_data.loc[(weather_data['Temp']>70)&(weather_data['Temp']<80)&(weather_data['Wind']<10)&
                 (weather_data['Cloud']<1)
                 ]
weath_dat

,Unnamed: 0,City,Lon,Lat,Temp,Humidity,Wind,Cloud
44,44,Mormugao,73.80,15.40,74.73,65,1.66,0
180,180,Takoradi,-1.76,4.88,75.31,89,2.26,0
187,187,Yenagoa,6.26,4.92,72.10,87,3.31,0
231,231,Axim,-2.24,4.87,75.31,89,2.26,0
361,361,Kralendijk,-68.27,12.15,78.80,83,5.82,0
389,389,Beloha,45.05,-25.17,73.09,66,7.09,0
396,396,Santiago,-70.65,-33.46,77.00,44,5.82,0
427,427,Sao felix do xingu,-51.99,-6.64,73.47,90,0.96,0
462,462,Beitbridge,30.00,-22.22,77.74,48,2.39,0
498,498,Chiredzi,31.67,-21.05,72.88,56,2.66,0

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [41]:
url = "https://maps.googleapis.com/maps/api/place/textsearch/json?"
hotels=[]
for i in range(0,len(weath_dat)):
    query = 'Lodging in '+list(weath_dat['City'])[i]

    r = requests.get(url + 'query=' + query +
                        '&key=' + g_key) 
    x= r.json()['results']
    hotels.append(x[0]['name'])

In [44]:
weath_dat['Hotels']=hotels

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [47]:
weath_dat

,Unnamed: 0,City,Lon,Lat,Temp,Humidity,Wind,Cloud,Hotels
44,44,Mormugao,73.80,15.40,74.73,65,1.66,0,Bogmallo Beach Resort
180,180,Takoradi,-1.76,4.88,75.31,89,2.26,0,Protea Hotel by Marriott Takoradi Select
187,187,Yenagoa,6.26,4.92,72.10,87,3.31,0,De Brass Suites
231,231,Axim,-2.24,4.87,75.31,89,2.26,0,Axim Beach Hotel
361,361,Kralendijk,-68.27,12.15,78.80,83,5.82,0,One Ocean Boutique Apartments & Suites
389,389,Beloha,45.05,-25.17,73.09,66,7.09,0,Sharron Bungalow
396,396,Santiago,-70.65,-33.46,77.00,44,5.82,0,Plaza Paris Amistar
427,427,Sao felix do xingu,-51.99,-6.64,73.47,90,0.96,0,Apart Hotel Rio Xingu
462,462,Beitbridge,30.00,-22.22,77.74,48,2.39,0,"Elliot Hotel&Conference Centre,Beit Bridge"
498,498,Chiredzi,31.67,-21.05,72.88,56,2.66,0,The Nesbitt Arms

In [7]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

NameError: name 'narrowed_city_df' is not defined

In [ ]:
# Add marker layer ontop of heat map


# Display Map